# Generated by Django 4.2.4 on 2024-02-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_participant_options_participant_pj'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='cnpj',
            field=models.CharField(default=1000000000000, max_length=45, verbose_name='CNPJ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manager',
            name='email_manager',
            field=models.EmailField(default='', max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone_manager',
            field=models.CharField(default='', max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='profile_manager',
            field=models.CharField(default='', max_length=255, verbose_name='Manager Name'),
        ),
    ]
