# Generated by Django 4.2.4 on 2024-02-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_manager_cnpj_alter_manager_email_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
    ]
