# Generated by Django 4.2.4 on 2024-01-25 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='instance_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='project.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='questioninstance',
            name='instance_pj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_instance', to='question.instance'),
        ),
    ]
