# Generated by Django 4.2.4 on 2024-01-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_instance_instance_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioninstance',
            name='instance_pj',
        ),
        migrations.RemoveField(
            model_name='questioninstance',
            name='question_pj',
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
        migrations.DeleteModel(
            name='QuestionInstance',
        ),
    ]
