# Generated by Django 4.2.4 on 2024-02-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_question_situation_alter_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='situation',
        ),
    ]
