# Generated by Django 4.2.4 on 2024-02-27 13:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Generating situation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instance',
                'verbose_name_plural': 'Instances',
            },
        ),
        migrations.CreateModel(
            name='InstanceAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_attempt', models.IntegerField(default=0, verbose_name='Status Attempt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instance Attempt',
                'verbose_name_plural': 'Instance Attempts',
            },
        ),
        migrations.CreateModel(
            name='InstanceAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likert_scale', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, null=True, verbose_name='Likert scale')),
                ('attempt_number', models.IntegerField(default=1, verbose_name='Attempt number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance_attempt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances_attempt_answer', to='instance.instanceattempt', verbose_name='Instance Attempt')),
            ],
            options={
                'verbose_name': 'Instance Attempt Answer',
                'verbose_name_plural': 'Instance Attempt Answers',
            },
        ),
    ]
