# Generated by Django 4.2.4 on 2024-02-27 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        ('instance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceattemptanswer',
            name='option_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_answer', to='question.option', verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='instanceattemptanswer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_answer', to='question.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='instanceattempt',
            name='instance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances_answer', to='instance.instance', verbose_name='Instance'),
        ),
    ]
