# Generated by Django 4.2.4 on 2024-02-11 13:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_participant_options_participant_pj'),
        ('question', '0003_remove_questioninstance_instance_pj_and_more'),
        ('instance', '0002_instance_description_alter_instance_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likert_scale', models.IntegerField(default=1, max_length=10, verbose_name='Rating scale')),
                ('attempt_number', models.IntegerField(default=1, max_length=10, verbose_name='Attempt number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance_attempt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances_attempt_answer', to='instance.instance')),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_answer', to='question.option')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_answer', to='question.question')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_attempt', models.IntegerField(default=0, max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances_answer', to='instance.instance')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_answer', to='users.participant')),
            ],
        ),
    ]
