# Generated by Django 4.2.4 on 2024-02-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0003_instanceattemptanswer_instanceattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceattempt',
            name='status_attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instanceattemptanswer',
            name='attempt_number',
            field=models.IntegerField(default=1, verbose_name='Attempt number'),
        ),
        migrations.AlterField(
            model_name='instanceattemptanswer',
            name='likert_scale',
            field=models.IntegerField(default=1, verbose_name='Rating scale'),
        ),
    ]
