# Generated by Django 4.2.4 on 2024-02-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_participant_options_participant_pj'),
        ('instance', '0004_alter_instanceattempt_status_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='instanceattempt',
            name='instance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances_answer', to='instance.instance', verbose_name='Instance'),
        ),
        migrations.AlterField(
            model_name='instanceattempt',
            name='status_attempt',
            field=models.IntegerField(default=0, verbose_name='Status Attempt'),
        ),
        migrations.AlterField(
            model_name='instanceattempt',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_answer', to='users.participant', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='instanceattemptanswer',
            name='instance_attempt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances_attempt_answer', to='instance.instanceattempt'),
        ),
    ]
