# Generated by Django 4.2.4 on 2024-02-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0005_alter_instanceattempt_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceattemptanswer',
            name='likert_scale',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Rating scale'),
        ),
    ]
