# Generated by Django 4.2.4 on 2024-02-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_remove_questioninstance_instance_pj_and_more'),
        ('instance', '0006_alter_instanceattemptanswer_likert_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceattemptanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='instanceattemptanswer',
            name='instance_attempt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances_attempt_answer', to='instance.instanceattempt', verbose_name='Instance Attempt'),
        ),
        migrations.AlterField(
            model_name='instanceattemptanswer',
            name='likert_scale',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Likert scale'),
        ),
        migrations.AlterField(
            model_name='instanceattemptanswer',
            name='option_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_answer', to='question.option', verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='instanceattemptanswer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_answer', to='question.question', verbose_name='Question'),
        ),
    ]
