# Generated by Django 4.2.4 on 2024-02-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0007_alter_instanceattemptanswer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceattemptanswer',
            name='likert_scale',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, null=True, verbose_name='Likert scale'),
        ),
    ]
