# Generated by Django 4.2.4 on 2024-02-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0009_alter_instanceattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Generating situation'),
        ),
    ]
