# Generated by Django 4.2.4 on 2024-02-27 13:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pj_name', models.CharField(max_length=255, verbose_name='Project name')),
                ('pj_code', models.PositiveIntegerField(unique=True, verbose_name='Project code')),
                ('pj_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-pk'],
            },
        ),
    ]
